wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/vqa.py
    python_version: 3.10.10
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707873738.499851
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 13
      - 23
      - 35
      4: 3.10.10
      5: 0.16.3
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
